aquaman/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # 메인 홈페이지로 이동
    path('manager/', include('manager.urls')),  # Manager 앱으로 이동    
    path('user/', include('user.urls')),  # User 앱으로 이동,
    path('recognition/', include('recognition.urls')),
    path('disease/', include('disease.urls')),
    path('prediction/', include('prediction.urls')),
]

disease/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'disease'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', views.main_view, name='main'),
    path('upload_csv/', views.main_view, name='upload_csv'),
    path('result/', views.result_view, name='result'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
]

prediction/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'prediction'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', views.main_view, name='main'),
    path('upload_csv/', views.main_view, name='upload_csv'),
    path('result/', views.result_view, name='result'),
]

recognition/urls.py
from django.urls import path
from . import views

app_name = 'recognition'

urlpatterns = [
    path('main/', views.main_view, name='main'),
    path('result/', views.result_view, name='result'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('signup_success/', views.signup_success, name='signup_success'),
    path('main/', views.main_view, name='main'),
    # 추가 기능을 위한 URL 설정도 여기에 포함될 수 있습니다.
]

recognition/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from ultralytics import YOLO
from PIL import Image
import os
import shutil

recognition_model = YOLO('recognition/model/recognition.pt')
disease_model = YOLO('recognition/model/disease.pt')

@login_required
def main_view(request):
    #이미지 입력 응답이 들어오면
    if request.method == 'POST' and request.FILES['image']:
        
        #기존 disease 결과 이미지 제거
        static_dir = os.path.join(os.getcwd(), 'static')
        image_files = [f for f in os.listdir(static_dir) if f.endswith(('.png', '.jpg', '.jpeg'))]
        for file_name in image_files:
            file_path = os.path.join(static_dir, file_name)
            os.remove(file_path)
        
        image_file = request.FILES['image']
        fs = FileSystemStorage()
        rfilename = fs.save(image_file.name, image_file)
        image_path = fs.path(rfilename)
        source = Image.open(image_path)
        
        #recognition 모델
        results = recognition_model(source)
        
        recognition_directory = '넙치'
        
        #recognition 모델 결과 저장
        for result in results:
            result.save_crop(save_dir = os.getcwd())
        
        for filename in os.listdir(recognition_directory):
            if filename.endswith('.jpg') or filename.endswith('.png'):  # 이미지 파일 확인
                image_path = os.path.join(recognition_directory, filename)  # 파일의 전체 경로
                source = Image.open(image_path)
                
                #disease 모델
                results = disease_model(source)
                
                #diease 모델 결과 저장
                for result in results:
                    result.save()
                    
        #recognition 모델 결과 폴더 제거
        shutil.rmtree(recognition_directory)
        
        # 결과 이미지 파일을 static 폴더로 이동
        image_files = [f for f in os.listdir(os.getcwd()) if f.endswith(('.png', '.jpg', '.jpeg'))]
        for file_name in image_files:
            source_path = os.path.join(os.getcwd(), file_name)
            target_path = os.path.join(os.getcwd(), 'static', file_name)
            shutil.move(source_path, target_path)
        
        return redirect('recognition:result')
    return render(request, 'recognition/main.html')

@login_required
def result_view(request):
    static_dir = os.path.join(os.getcwd(), 'static')
    
    # static 디렉토리 내의 모든 이미지 파일 리스트
    image_files = [f for f in os.listdir(static_dir) if f.endswith(('.png', '.jpg', '.jpeg'))]

    # 이미지 파일의 URL 리스트 생성
    image_urls = [os.path.join('/static', file_name) for file_name in image_files]

    return render(request, 'recognition/result.html', {'image_urls': image_urls})

recognition/templates/recognition/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Disease Detection</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <style>
        body {
            background-color: #f2f2f2;
        }

        .search-container {
            background-color: #ffffff;
            border-bottom: 1px solid #e0e0e0;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            position: fixed;
            top: 0;
            left: 302px;
            width: calc(100% - 280px);
            z-index: 1;
        }

        .search-input-container {
            position: relative;
            width: 500px;
        }

        .search-input {
            width: 100%;
            height: 40px;
            padding-left: 40px;
            border: 1px solid #e0e0e0;
            outline: none;
            background-color: #ffffff;
        }

        .search-icon {
            position: absolute;
            left: 10px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 20px;
            color: #666666;
        }

        .sidebar {
            background-color: #ffffff;
            color: #000000;
            position: fixed;
            top: 0;
            left: 0;
            height: 100vh;
            z-index: 2;
            width: 300px;
        }

        .nav-link {
            display: flex;
            align-items: center;
            color: #000000;
            transition: color 0.3s ease-in-out;
        }

        .nav-link:hover {
            color: #007bff;
        }

        .nav-link i,
        .nav-link span {
            transition: color 0.3s ease-in-out;
        }

        .nav-link:hover i,
        .nav-link:hover span {
            color: #007bff;
        }

        .content-container {
            margin-top: 80px;
            margin-left: 320px;
            padding: 20px;
        }

        .table-container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .table th,
        .table td {
            vertical-align: middle;
        }
        /* 이미지와 description 사이의 간격 조정 */
        .table td {
            padding: 5px; /* 이미지와 description 사이의 간격을 조정합니다. */
        }

        /* 이미지와 설명 간격을 좁히기 위한 스타일 */
        .table td {
            vertical-align: top; /* 이미지와 설명을 상단에 정렬합니다. */
        }

        .table img {
            display: block; /* 이미지를 블록 요소로 변경하여 위아래 간격이 생기지 않도록 합니다. */
            margin-bottom: 10px; /* 이미지 아래에 10px 간격을 추가합니다. */
        }

        .table td .form-group {
            margin-left: 5px;
            margin-bottom: 0; /* 입력 폼의 하단 여백을 제거합니다. */
        }

        .update-button-container {
            margin-left: 520px;
            right: 20px;
        }
        /* 파일 선택 레이블의 스타일 수정 */
        #file-label {
            display: block; /* 블록 요소로 설정하여 이미지 아래에 배치 */
            margin-top: 10px; /* 이미지와의 간격 조정 */
            text-align: center; /* 가운데 정렬 */
        }
        .form-control {
            width: 100%;
        }
        .form-group {
            width: 100%;
        }
    </style>
</head>
<body>
<div class="sidebar d-flex flex-column flex-shrink-0 p-3 text-black" style="width: 300px; height: 100vh;">
    <div class="d-flex justify-content-center">
        <img src="/static/img/사이드바로고.png" alt="Logo" class="mb-3" style="width: 105%; height: auto;">
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a class="nav-link text-black" aria-current="page" onclick="window.location.href='{% url 'home' %}'">
                <i class="bi bi-house"></i>
                <span class="ms-1">Home</span>
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'recognition:main' %}" class="nav-link text-black">
                <i class="bi bi-eye"></i>
                <span class="ms-1">질병 감지</span>
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'disease:main' %}" class="nav-link text-black">
                <i class="bi bi-bar-chart-line"></i>
                <span class="ms-1">질병 예측</span>
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'prediction:main' %}" class="nav-link text-black">
                <i class="bi bi-arrow-up-right-circle"></i>
                <span class="ms-1">성장 예측</span>
            </a>
        </li>
        <br>
        <li>
            <a href="#" class="nav-link text-black">
                <i class="bi bi-card-checklist"></i>
                <span class="ms-1">이전 기록</span>
            </a>
        </li>
    </ul>

    <!-- if not signed in -->
    <ul class="nav nav-pills flex-column mb-3">
        <li class="nav-item">
            <a href="{% url 'user:logout' %}" class="nav-link text-black">
                <i class="bi bi-box-arrow-right"></i>
                <span class="ms-2 fs-6">Log out</span>
            </a>
        </li>
    </ul>
    <!-- if signed in -->
</div>

<div class="content-container">
    <div class="table-container">
        <h2><b>질병 감지</b></h2>
        <br>
        <h4><b>이미지 업로드</b></h4>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <img id="preview-image" src="/static/img/default_image.png" alt="Default Image" style="max-width: 400px; height: auto;">
            <br><br>
            <input type="file" name="image" id="fish-image" accept="image/*" required>
            <div class="update-button-container">
                <button type="submit" class="btn btn-primary" id="update-button">업로드</button>
            </div>
        </form>
    </div>
</div>

<script>
    // 파일 선택 input 변경시 이미지 미리보기 업데이트
    document.getElementById('fish-image').addEventListener('change', function(event) {
        var selectedFile = event.target.files[0];
        var previewImage = document.getElementById('preview-image');
        var fileLabel = document.getElementById('file-label');

        if (selectedFile) {
            var reader = new FileReader();
            reader.onload = function(event) {
                previewImage.src = event.target.result;
            };
            reader.readAsDataURL(selectedFile);
            fileLabel.textContent = selectedFile.name;
        } else {
            previewImage.src = "/static/img/default_image.png";
            fileLabel.textContent = "파일 선택";
        }
    });

    window.addEventListener('scroll', function() {
        var searchContainer = document.getElementById('search-container');
        var contentContainer = document.getElementById('content-container');

        if (window.scrollY > 0) {
            searchContainer.style.position = 'fixed';
            contentContainer.style.marginTop = '60px';
        } else {
            searchContainer.style.position = 'absolute';
            contentContainer.style.marginTop = '50px';
        }
    });

    document.getElementById('update-button').addEventListener('click', function() {
        // 여기에 테이블 데이터를 업데이트하는 코드를 추가합니다.
        console.log('Table updated!');
    });

</script>

</body>
</html>

recognition/templates/recognition/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Disease Detection Result</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <style>
        body {
            background-color: #f2f2f2;
        }

        .search-container {
            background-color: #ffffff;
            border-bottom: 1px solid #e0e0e0;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            position: fixed;
            top: 0;
            left: 302px;
            width: calc(100% - 280px);
            z-index: 1;
        }

        .search-input-container {
            position: relative;
            width: 500px;
        }

        .search-input {
            width: 100%;
            height: 40px;
            padding-left: 40px;
            border: 1px solid #e0e0e0;
            outline: none;
            background-color: #ffffff;
        }

        .search-icon {
            position: absolute;
            left: 10px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 20px;
            color: #666666;
        }

        .sidebar {
            background-color: #ffffff;
            color: #000000;
            position: fixed;
            top: 0;
            left: 0;
            height: 100vh;
            z-index: 2;
            width: 300px;
        }

        .nav-link {
            display: flex;
            align-items: center;
            color: #000000;
            transition: color 0.3s ease-in-out;
        }

        .nav-link:hover {
            color: #007bff;
        }

        .nav-link i,
        .nav-link span {
            transition: color 0.3s ease-in-out;
        }

        .nav-link:hover i,
        .nav-link:hover span {
            color: #007bff;
        }

        .content-container {
            margin-top: 80px;
            margin-left: 320px;
            padding: 20px;
        }

        .table-container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .table th,
        .table td {
            vertical-align: middle;
        }
        /* 이미지와 description 사이의 간격 조정 */
        .table td {
            padding: 5px; /* 이미지와 description 사이의 간격을 조정합니다. */
        }

        /* 이미지와 설명 간격을 좁히기 위한 스타일 */
        .table td {
            vertical-align: top; /* 이미지와 설명을 상단에 정렬합니다. */
        }

        .table img {
            display: block; /* 이미지를 블록 요소로 변경하여 위아래 간격이 생기지 않도록 합니다. */
            margin-bottom: 10px; /* 이미지 아래에 10px 간격을 추가합니다. */
        }

        .table td .form-group {
            margin-left: 5px;
            margin-bottom: 0; /* 입력 폼의 하단 여백을 제거합니다. */
        }

        .update-button-container {
            margin-left: 520px;
            right: 20px;
        }
        /* 파일 선택 레이블의 스타일 수정 */
        #file-label {
            display: block; /* 블록 요소로 설정하여 이미지 아래에 배치 */
            margin-top: 10px; /* 이미지와의 간격 조정 */
            text-align: center; /* 가운데 정렬 */
        }
        .form-control {
            width: 100%;
        }
        .form-group {
            width: 100%;
        }
    </style>
</head>
<body>
<div class="sidebar d-flex flex-column flex-shrink-0 p-3 text-black" style="width: 300px; height: 100vh;">
    <div class="d-flex justify-content-center">
        <img src="/static/img/사이드바로고.png" alt="Logo" class="mb-3" style="width: 105%; height: auto;">
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a class="nav-link text-black" aria-current="page" onclick="window.location.href='{% url 'home' %}'">
                <i class="bi bi-house"></i>
                <span class="ms-1">Home</span>
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'recognition:main' %}" class="nav-link text-black">
                <i class="bi bi-eye"></i>
                <span class="ms-1">질병 감지</span>
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'disease:main' %}" class="nav-link text-black">
                <i class="bi bi-bar-chart-line"></i>
                <span class="ms-1">질병 예측</span>
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'prediction:main' %}" class="nav-link text-black">
                <i class="bi bi-arrow-up-right-circle"></i>
                <span class="ms-1">성장 예측</span>
            </a>
        </li>
        <br>
        <li>
            <a href="#" class="nav-link text-black">
                <i class="bi bi-card-checklist"></i>
                <span class="ms-1">이전 기록</span>
            </a>
        </li>
    </ul>

    <!-- if not signed in -->
    <ul class="nav nav-pills flex-column mb-3">
        <li class="nav-item">
            <a href="{% url 'user:logout' %}" class="nav-link text-black">
                <i class="bi bi-box-arrow-right"></i>
                <span class="ms-2 fs-6">Log out</span>
            </a>
        </li>
    </ul>
    <!-- if signed in -->
</div>

<div class="content-container">
    <div class="table-container">
        <h2><b>질병 감지 결과</b></h2>
        <br>
        <div>
            {% for image_url in image_urls %}
                <img src="{{ image_url }}" alt="Recognition Result Image" style="width: 200px; height: auto;">
            {% endfor %}
        </div>
    </div>
</div>

<script>
    window.addEventListener('scroll', function() {
        var searchContainer = document.getElementById('search-container');
        var contentContainer = document.getElementById('content-container');

        if (window.scrollY > 0) {
            searchContainer.style.position = 'fixed';
            contentContainer.style.marginTop = '60px';
        } else {
            searchContainer.style.position = 'absolute';
            contentContainer.style.marginTop = '50px';
        }
    });

    document.getElementById('update-button').addEventListener('click', function() {
        // 여기에 테이블 데이터를 업데이트하는 코드를 추가합니다.
        console.log('Table updated!');
    });

</script>

</body>
</html>